version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - db
    networks:
      - kaleidoscope-net

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    networks:
      - kaleidoscope-net

  db:
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - kaleidoscope-net

volumes:
  redis-data:
  postgres-data:

networks:
  kaleidoscope-net:
    driver: bridge
